server:
  port: 8082

spring:
  application:
    name: store-user-service

  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: Start#123

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

  flyway:
    table: flyway_schema_history_user
    baseline-on-migrate: true

logging:
  level:
    com.codewithmosh.store.user: DEBUG
